"""
Multi-floor graph construction (PHASE 6).

Builds one navigable graph spanning every active Map in a single
MapGroup: same-floor walkway edges plus explicit vertical-connector
transition edges (RouteEdge.connector_id set / to_map_id set). Nodes are
always keyed by RoutePoint database id — never by name, never by
coordinates — and node/edge metadata (map_id, floor, x, y, point_type,
edge_type, distance, time, accessibility, direction) is preserved
verbatim from the underlying documents so the router and instruction
generator never need a second lookup.

This module never merges coordinates across maps and never infers a
connection between two points just because they are close — the only
edges in the graph are ones that already exist as real RouteEdge
documents (drawn by an admin, or generated by
services/vertical_connector_service.py from an explicit connector stop).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, FrozenSet, List, Optional

from beanie import PydanticObjectId

from models.map_model import Map
from models.route_edge_model import RouteEdge
from models.route_point_model import RoutePoint
from logic.routing_cost import edge_routing_weight, edge_time_seconds, is_edge_usable


@dataclass
class GraphNode:
    id: str
    map_id: str
    floor: Optional[int]
    x: float
    y: float
    point_type: Optional[str]
    name: str
    is_accessible: bool
    display_name: Optional[str] = None
    is_auto_generated: bool = False
    # Per-language display names (Section 16 of the semantic-map-analysis
    # spec / multilingual content spec) — purely additive presentation
    # data carried alongside the existing single `display_name`, never
    # used for routing/weight/topology decisions. See
    # logic/instruction_generator.resolve_localized_display_name.
    display_name_en: Optional[str] = None
    display_name_ar: Optional[str] = None
    display_name_he: Optional[str] = None
    # Nested-room navigation (Approved Semantic Analysis -> Automatic
    # Destinations spec, Section 9/13) — mirrors RoutePoint.
    # allow_transit_through verbatim. False for every point except an
    # explicitly admin-approved "outer" pass-through room. Consulted only
    # by logic/multi_floor_routing.py's
    # _suppress_intermediate_destination_nodes; Dijkstra itself never reads
    # this field.
    allow_transit_through: bool = False


@dataclass
class GraphEdgeRef:
    edge: RouteEdge
    to_node_id: str
    weight: float
    time_seconds: float


@dataclass
class MultiFloorGraph:
    nodes: Dict[str, GraphNode] = field(default_factory=dict)
    adjacency: Dict[str, List[GraphEdgeRef]] = field(default_factory=dict)
    maps_by_id: Dict[str, Map] = field(default_factory=dict)


async def build_multi_floor_graph(
    map_ids: List[str],
    *,
    mode: str = "shortest",
    accessible_only: bool = False,
    avoid_edge_types: Optional[FrozenSet[str]] = None,
) -> MultiFloorGraph:
    """
    `map_ids` is the exact, already-resolved set of Map documents this
    graph may span — either every floor of one MapGroup, or a single
    ungrouped map (same-floor-only request). Never resolved from a
    map_group_id query here, so an ungrouped map (map_group_id=None)
    can never accidentally be scoped alongside every OTHER ungrouped map
    in the whole system.
    """

    maps = await Map.find(
        {"_id": {"$in": [PydanticObjectId(m) for m in map_ids]}}
    ).to_list()

    graph = MultiFloorGraph()
    graph.maps_by_id = {str(m.id): m for m in maps}

    if not maps:
        return graph

    map_ids = list(graph.maps_by_id.keys())

    points = await RoutePoint.find(
        {"map_id": {"$in": map_ids}, "is_active": True}
    ).to_list()

    for point in points:
        graph.nodes[str(point.id)] = GraphNode(
            id=str(point.id),
            map_id=point.map_id,
            floor=point.floor,
            x=point.x,
            y=point.y,
            point_type=point.point_type,
            name=point.name,
            is_accessible=point.is_accessible,
            display_name=point.display_name,
            is_auto_generated=point.is_auto_generated,
            display_name_en=point.display_name_en,
            display_name_ar=point.display_name_ar,
            display_name_he=point.display_name_he,
            allow_transit_through=point.allow_transit_through,
        )
        graph.adjacency.setdefault(str(point.id), [])

    edges = await RouteEdge.find(
        {
            "$or": [
                {"map_id": {"$in": map_ids}},
                {"to_map_id": {"$in": map_ids}},
            ]
        }
    ).to_list()

    for edge in edges:
        if not is_edge_usable(
            edge, accessible_only=accessible_only, avoid_edge_types=avoid_edge_types
        ):
            continue

        from_id = edge.from_point_id
        to_id = edge.to_point_id

        # Both endpoints must actually be loaded nodes (active points on
        # an active map of this group) — an edge referencing a point
        # outside this group/inactive is silently skipped rather than
        # crashing the whole route request.
        if from_id not in graph.nodes or to_id not in graph.nodes:
            continue

        weight = edge_routing_weight(edge, mode=mode)
        time_seconds = edge_time_seconds(edge)

        graph.adjacency.setdefault(from_id, []).append(
            GraphEdgeRef(edge=edge, to_node_id=to_id, weight=weight, time_seconds=time_seconds)
        )

        if edge.is_bidirectional:
            graph.adjacency.setdefault(to_id, []).append(
                GraphEdgeRef(edge=edge, to_node_id=from_id, weight=weight, time_seconds=time_seconds)
            )

    return graph
