// EN/AR/HE copy for the whole admin shell — the shared sidebar, the
// identity header, every admin page header and the dashboard screens.
// Kept in one module so a string has exactly one home and so the legacy
// screens that are now inside the shell can reuse the same Back/breadcrumb
// wording instead of each carrying its own copy.
//
// The shared LangContext still drives which language is active, so language
// switching and RTL behave exactly as before.

const dashboardUi = {
  en: {
    dir: 'ltr',
    roles: {
      super_admin: 'Super Admin',
      global_manager: 'Global Manager',
      building_manager: 'Building Manager',
    },
    nav: {
      overview: 'Overview',
      sites: 'Sites & Buildings',
      mapManagement: 'Map Management',
      invitations: 'Invitation Codes',
      users: 'Users & Access',
      logout: 'Logout',
    },
    back: 'Back',
    welcome: (name) => (name ? `Welcome back, ${name}` : 'Welcome back'),
    welcomeSub: 'Manage all your locations from one place',
    stats: {
      sites: 'Sites',
      sitesHint: 'In your scope',
      buildings: 'Buildings',
      buildingsHint: 'Across your sites',
      mapGroups: 'Map Groups',
      mapGroupsHint: 'Across your buildings',
      floors: 'Floors',
      floorsHint: 'Maps you can manage',
    },
    sitesTitle: 'Your Sites',
    sitesSub: 'Organize and access all your locations',
    pages: {
      sites: { title: 'Sites & Buildings', desc: 'Create, edit and open the buildings in your scope' },
      mapManagement: { title: 'Map Management', desc: 'Upload floor plans, create map groups and add floors' },
      invitations: { title: 'Invitation Codes', desc: 'Create signup codes and assign roles and scope' },
      users: { title: 'Users & Access', desc: 'Manage administrators and their assigned access' },
      rooms: { title: 'Rooms & Destinations', desc: 'Manage destinations and their placement' },
      routes: { title: 'Route Points', desc: 'Manage navigation nodes and connections' },
      locationCodes: { title: 'Location Codes', desc: 'Barcode/QR start points' },
      analysis: { title: 'Semantic Analysis', desc: 'Run and review map analysis' },
      cleanup: { title: 'Navigation Data Cleanup', desc: 'Remove generated data or reset navigation' },
    },
    usersAccess: {
      searchPlaceholder: 'Search by name or email…',
      roleAll: 'All roles',
      colName: 'Name',
      colEmail: 'Email',
      colRole: 'Role',
      colResponsibility: 'Responsibility',
      colActions: '',
      edit: 'Edit',
      delete: 'Delete',
      empty: 'No administrators match this view',
      emptyHint: 'Invite an administrator from Invitation Codes',
      loadError: 'Failed to load administrators',
      scope: {
        system_wide: 'System-wide',
        project_wide: 'Global administration',
        all_buildings: 'Global administration (all buildings)',
        buildings: 'Scoped global administration',
        building: '',
        unassigned: 'No building assigned',
        legacy_maps: 'Legacy scope — specific maps only',
        legacy_map_groups: 'Legacy scope — specific map groups only',
        legacy_multi_building: 'Legacy scope — several buildings',
        none: '—',
      },
      editTitle: 'Edit User',
      fullName: 'Full Name',
      role: 'Role',
      assignedBuilding: 'Assigned Building',
      selectBuilding: 'Select a building…',
      cancel: 'Cancel',
      save: 'Save Changes',
      saving: 'Saving…',
      saveError: 'Failed to save changes',
      deleteTitle: (name) => `Delete ${name}?`,
      deleteBody: 'This user will lose access to QuickRoute. This action cannot be undone.',
      deleteConfirm: 'Delete User',
      deleteError: 'Failed to delete this user',
    },
    buildingWorkspace: {
      groups: 'Map Groups',
      groupsSub: 'Open a floor to reach its navigation tools',
    },
    floorWorkspace: {
      toolsTitle: 'Tools for this map',
      toolsSub: 'Only the tools you are allowed to use on this map',
      dangerTitle: 'Danger zone',
      dangerDesc:
        'Permanently remove generated navigation data, or reset navigation for this map. This action cannot be undone.',
      dangerAction: 'Open Cleanup',
    },
    context: {
      site: 'Site',
      building: 'Building',
      mapGroup: 'Map Group',
      floor: 'Floor',
      category: 'Category',
    },
    labels: {
      buildings: 'Buildings',
      mapGroups: 'Map Groups',
      floors: 'Floors',
      active: 'Active',
      inactive: 'Inactive',
      allCategories: 'All',
      uncategorized: 'Uncategorized',
      unassignedSite: 'Unspecified site',
      floorPrefix: 'Floor',
      floorCount: (n) => `${n} floor${n === 1 ? '' : 's'}`,
      open: 'Open',
    },
    states: {
      loading: 'Loading…',
      noSites: 'No buildings yet',
      noSitesHint: 'Create a building to start organizing your locations',
      noBuildings: 'No buildings in this site yet',
      noMapGroups: 'No map groups in this building yet',
      noMapGroupsHint: 'Upload a floor plan in Map Management to create the first one',
      noFloors: 'No floors in this map group yet',
      noScope: 'No buildings are assigned to this account',
      noScopeHint: 'Contact a Super Admin to be assigned to a building',
      notFound: 'This item is not available',
      notFoundHint: 'It may have been removed, or it is outside your assigned scope',
      loadError: 'Failed to load dashboard data',
      forbidden: 'You do not have permission to view this.',
      sessionExpired: 'Your session has expired. Please log in again.',
    },
    actions: {
      manageBuildings: 'Add building',
      openMapManagement: 'Map Management',
      uploadMap: 'Upload map',
    },
    tools: {
      workspace: { title: 'Map Workspace', desc: 'Draw and edit this map’s navigation graph' },
      rooms: { title: 'Rooms & Destinations', desc: 'Manage destinations and their placement' },
      routes: { title: 'Route Points', desc: 'Manage navigation nodes and connections' },
      locationCodes: { title: 'Location Codes', desc: 'Barcode/QR start points' },
      analysis: { title: 'Semantic Analysis', desc: 'Run and review map analysis' },
      cleanup: { title: 'Navigation Data Cleanup', desc: 'Remove generated data or reset navigation' },
    },
  },

  ar: {
    dir: 'rtl',
    roles: {
      super_admin: 'مشرف عام',
      global_manager: 'مدير عام',
      building_manager: 'مدير مبنى',
    },
    nav: {
      overview: 'نظرة عامة',
      sites: 'المواقع والمباني',
      mapManagement: 'إدارة الخرائط',
      invitations: 'رموز الدعوة',
      users: 'المستخدمون والصلاحيات',
      logout: 'تسجيل خروج',
    },
    back: 'رجوع',
    welcome: (name) => (name ? `أهلاً بعودتك، ${name}` : 'أهلاً بعودتك'),
    welcomeSub: 'أدر جميع مواقعك من مكان واحد',
    stats: {
      sites: 'المواقع',
      sitesHint: 'ضمن نطاقك',
      buildings: 'المباني',
      buildingsHint: 'في مواقعك',
      mapGroups: 'مجموعات الخرائط',
      mapGroupsHint: 'في مبانيك',
      floors: 'الطوابق',
      floorsHint: 'الخرائط التي يمكنك إدارتها',
    },
    sitesTitle: 'مواقعك',
    sitesSub: 'نظّم مواقعك وادخل إليها',
    pages: {
      sites: { title: 'المواقع والمباني', desc: 'أنشئ وحرّر وافتح المباني ضمن نطاقك' },
      mapManagement: { title: 'إدارة الخرائط', desc: 'ارفع مخططات الطوابق وأنشئ مجموعات خرائط وأضف طوابق' },
      invitations: { title: 'رموز الدعوة', desc: 'أنشئ رموز تسجيل وحدد الأدوار والنطاق' },
      users: { title: 'المستخدمون والصلاحيات', desc: 'إدارة المشرفين والصلاحيات الممنوحة لهم' },
      rooms: { title: 'الغرف والوجهات', desc: 'إدارة الوجهات وأماكنها' },
      routes: { title: 'نقاط المسار', desc: 'إدارة عقد التنقل والوصلات' },
      locationCodes: { title: 'رموز المواقع', desc: 'نقاط بدء باركود/QR' },
      analysis: { title: 'التحليل الدلالي', desc: 'تشغيل ومراجعة تحليل الخريطة' },
      cleanup: { title: 'تنظيف بيانات التنقل', desc: 'حذف البيانات المولّدة أو إعادة ضبط التنقل' },
    },
    usersAccess: {
      searchPlaceholder: 'ابحث بالاسم أو البريد…',
      roleAll: 'كل الأدوار',
      colName: 'الاسم',
      colEmail: 'البريد الإلكتروني',
      colRole: 'الدور',
      colResponsibility: 'المسؤولية',
      colActions: '',
      edit: 'تعديل',
      delete: 'حذف',
      empty: 'لا يوجد مشرفون مطابقون',
      emptyHint: 'ادعُ مشرفاً من رموز الدعوة',
      loadError: 'فشل تحميل المشرفين',
      scope: {
        system_wide: 'على مستوى النظام',
        project_wide: 'إدارة عامة',
        all_buildings: 'إدارة عامة (كل المباني)',
        buildings: 'إدارة عامة ضمن نطاق',
        building: '',
        unassigned: 'لا يوجد مبنى مخصص',
        legacy_maps: 'نطاق قديم — خرائط محددة فقط',
        legacy_map_groups: 'نطاق قديم — مجموعات خرائط محددة فقط',
        legacy_multi_building: 'نطاق قديم — عدة مبانٍ',
        none: '—',
      },
      editTitle: 'تعديل المستخدم',
      fullName: 'الاسم الكامل',
      role: 'الدور',
      assignedBuilding: 'المبنى المخصص',
      selectBuilding: 'اختر مبنى…',
      cancel: 'إلغاء',
      save: 'حفظ التغييرات',
      saving: 'جارٍ الحفظ…',
      saveError: 'فشل حفظ التغييرات',
      deleteTitle: (name) => `حذف ${name}؟`,
      deleteBody: 'سيفقد هذا المستخدم صلاحية الوصول إلى QuickRoute. لا يمكن التراجع عن هذا الإجراء.',
      deleteConfirm: 'حذف المستخدم',
      deleteError: 'فشل حذف هذا المستخدم',
    },
    buildingWorkspace: {
      groups: 'مجموعات الخرائط',
      groupsSub: 'افتح طابقاً للوصول إلى أدوات التنقل الخاصة به',
    },
    floorWorkspace: {
      toolsTitle: 'أدوات هذه الخريطة',
      toolsSub: 'فقط الأدوات المسموح لك باستخدامها على هذه الخريطة',
      dangerTitle: 'منطقة خطرة',
      dangerDesc:
        'حذف نهائي للبيانات المولّدة أو إعادة ضبط بيانات التنقل لهذه الخريطة. لا يمكن التراجع عن هذا الإجراء.',
      dangerAction: 'فتح التنظيف',
    },
    context: {
      site: 'الموقع',
      building: 'المبنى',
      mapGroup: 'مجموعة الخرائط',
      floor: 'الطابق',
      category: 'التصنيف',
    },
    labels: {
      buildings: 'مبانٍ',
      mapGroups: 'مجموعات خرائط',
      floors: 'طوابق',
      active: 'نشط',
      inactive: 'غير نشط',
      allCategories: 'الكل',
      uncategorized: 'بدون تصنيف',
      unassignedSite: 'موقع غير محدد',
      floorPrefix: 'طابق',
      floorCount: (n) => `${n} طابق`,
      open: 'فتح',
    },
    states: {
      loading: 'جارٍ التحميل…',
      noSites: 'لا توجد مبانٍ بعد',
      noSitesHint: 'أنشئ مبنى للبدء بتنظيم مواقعك',
      noBuildings: 'لا توجد مبانٍ في هذا الموقع بعد',
      noMapGroups: 'لا توجد مجموعات خرائط في هذا المبنى بعد',
      noMapGroupsHint: 'ارفع مخطط طابق من إدارة الخرائط لإنشاء أول مجموعة',
      noFloors: 'لا توجد طوابق في مجموعة الخرائط هذه بعد',
      noScope: 'لا توجد مبانٍ مخصصة لهذا الحساب',
      noScopeHint: 'تواصل مع مشرف عام لتخصيص مبنى لك',
      notFound: 'هذا العنصر غير متاح',
      notFoundHint: 'ربما تم حذفه أو أنه خارج نطاقك المخصص',
      loadError: 'فشل تحميل بيانات اللوحة',
      forbidden: 'ليست لديك صلاحية لعرض هذا.',
      sessionExpired: 'انتهت جلستك. يرجى تسجيل الدخول مجدداً.',
    },
    actions: {
      manageBuildings: 'إضافة مبنى',
      openMapManagement: 'إدارة الخرائط',
      uploadMap: 'رفع خريطة',
    },
    tools: {
      workspace: { title: 'مساحة عمل الخريطة', desc: 'ارسم وحرّر شبكة التنقل لهذه الخريطة' },
      rooms: { title: 'الغرف والوجهات', desc: 'إدارة الوجهات وأماكنها' },
      routes: { title: 'نقاط المسار', desc: 'إدارة عقد التنقل والوصلات' },
      locationCodes: { title: 'رموز المواقع', desc: 'نقاط بدء باركود/QR' },
      analysis: { title: 'التحليل الدلالي', desc: 'تشغيل ومراجعة تحليل الخريطة' },
      cleanup: { title: 'تنظيف بيانات التنقل', desc: 'حذف البيانات المولّدة أو إعادة ضبط التنقل' },
    },
  },

  he: {
    dir: 'rtl',
    roles: {
      super_admin: 'מנהל-על',
      global_manager: 'מנהל גלובלי',
      building_manager: 'מנהל מבנה',
    },
    nav: {
      overview: 'סקירה',
      sites: 'אתרים ומבנים',
      mapManagement: 'ניהול מפות',
      invitations: 'קודי הזמנה',
      users: 'משתמשים והרשאות',
      logout: 'התנתק',
    },
    back: 'חזרה',
    welcome: (name) => (name ? `ברוך שובך, ${name}` : 'ברוך שובך'),
    welcomeSub: 'נהל את כל המיקומים שלך ממקום אחד',
    stats: {
      sites: 'אתרים',
      sitesHint: 'בהיקף שלך',
      buildings: 'מבנים',
      buildingsHint: 'באתרים שלך',
      mapGroups: 'קבוצות מפות',
      mapGroupsHint: 'במבנים שלך',
      floors: 'קומות',
      floorsHint: 'מפות שאתה יכול לנהל',
    },
    sitesTitle: 'האתרים שלך',
    sitesSub: 'ארגן וגש לכל המיקומים שלך',
    pages: {
      sites: { title: 'אתרים ומבנים', desc: 'צור, ערוך ופתח את המבנים בהיקף שלך' },
      mapManagement: { title: 'ניהול מפות', desc: 'העלה תוכניות קומה, צור קבוצות מפות והוסף קומות' },
      invitations: { title: 'קודי הזמנה', desc: 'צור קודי הרשמה והקצה תפקידים והיקף' },
      users: { title: 'משתמשים והרשאות', desc: 'ניהול מנהלים וההרשאות שהוקצו להם' },
      rooms: { title: 'חדרים ויעדים', desc: 'ניהול יעדים ומיקומם' },
      routes: { title: 'נקודות מסלול', desc: 'ניהול צמתי ניווט וחיבורים' },
      locationCodes: { title: 'קודי מיקום', desc: 'נקודות התחלה של ברקוד/QR' },
      analysis: { title: 'ניתוח סמנטי', desc: 'הרצה וסקירה של ניתוח המפה' },
      cleanup: { title: 'ניקוי נתוני ניווט', desc: 'הסרת נתונים שנוצרו או איפוס ניווט' },
    },
    usersAccess: {
      searchPlaceholder: 'חיפוש לפי שם או אימייל…',
      roleAll: 'כל התפקידים',
      colName: 'שם',
      colEmail: 'אימייל',
      colRole: 'תפקיד',
      colResponsibility: 'אחריות',
      colActions: '',
      edit: 'עריכה',
      delete: 'מחיקה',
      empty: 'אין מנהלים שתואמים לתצוגה הזו',
      emptyHint: 'הזמן מנהל דרך קודי הזמנה',
      loadError: 'טעינת המנהלים נכשלה',
      scope: {
        system_wide: 'כלל-מערכתי',
        project_wide: 'ניהול גלובלי',
        all_buildings: 'ניהול גלובלי (כל המבנים)',
        buildings: 'ניהול גלובלי מוגבל',
        building: '',
        unassigned: 'לא שויך מבנה',
        legacy_maps: 'היקף ישן — מפות מסוימות בלבד',
        legacy_map_groups: 'היקף ישן — קבוצות מפות מסוימות בלבד',
        legacy_multi_building: 'היקף ישן — כמה מבנים',
        none: '—',
      },
      editTitle: 'עריכת משתמש',
      fullName: 'שם מלא',
      role: 'תפקיד',
      assignedBuilding: 'מבנה משויך',
      selectBuilding: 'בחר מבנה…',
      cancel: 'ביטול',
      save: 'שמור שינויים',
      saving: 'שומר…',
      saveError: 'שמירת השינויים נכשלה',
      deleteTitle: (name) => `למחוק את ${name}?`,
      deleteBody: 'המשתמש הזה יאבד גישה ל-QuickRoute. לא ניתן לבטל את הפעולה.',
      deleteConfirm: 'מחק משתמש',
      deleteError: 'מחיקת המשתמש נכשלה',
    },
    buildingWorkspace: {
      groups: 'קבוצות מפות',
      groupsSub: 'פתח קומה כדי להגיע לכלי הניווט שלה',
    },
    floorWorkspace: {
      toolsTitle: 'כלים למפה הזו',
      toolsSub: 'רק הכלים שמותר לך להפעיל על המפה הזו',
      dangerTitle: 'אזור מסוכן',
      dangerDesc:
        'מחיקה קבועה של נתוני ניווט שנוצרו, או איפוס הניווט של המפה הזו. לא ניתן לבטל את הפעולה.',
      dangerAction: 'פתח ניקוי',
    },
    context: {
      site: 'אתר',
      building: 'מבנה',
      mapGroup: 'קבוצת מפות',
      floor: 'קומה',
      category: 'קטגוריה',
    },
    labels: {
      buildings: 'מבנים',
      mapGroups: 'קבוצות מפות',
      floors: 'קומות',
      active: 'פעיל',
      inactive: 'לא פעיל',
      allCategories: 'הכל',
      uncategorized: 'ללא קטגוריה',
      unassignedSite: 'אתר לא מוגדר',
      floorPrefix: 'קומה',
      floorCount: (n) => `${n} קומות`,
      open: 'פתח',
    },
    states: {
      loading: 'טוען…',
      noSites: 'אין עדיין מבנים',
      noSitesHint: 'צור מבנה כדי להתחיל לארגן את המיקומים שלך',
      noBuildings: 'אין עדיין מבנים באתר הזה',
      noMapGroups: 'אין עדיין קבוצות מפות במבנה הזה',
      noMapGroupsHint: 'העלה תוכנית קומה בניהול מפות כדי ליצור את הראשונה',
      noFloors: 'אין עדיין קומות בקבוצת המפות הזו',
      noScope: 'לא שויכו מבנים לחשבון הזה',
      noScopeHint: 'פנה למנהל-על כדי לשייך אליך מבנה',
      notFound: 'הפריט הזה אינו זמין',
      notFoundHint: 'ייתכן שהוסר, או שהוא מחוץ להיקף שהוקצה לך',
      loadError: 'טעינת נתוני הלוח נכשלה',
      forbidden: 'אין לך הרשאה לצפות בזה.',
      sessionExpired: 'הפעילות פגה. יש להתחבר מחדש.',
    },
    actions: {
      manageBuildings: 'הוסף מבנה',
      openMapManagement: 'ניהול מפות',
      uploadMap: 'העלאת מפה',
    },
    tools: {
      workspace: { title: 'סביבת עבודת מפה', desc: 'שרטוט ועריכה של גרף הניווט של המפה' },
      rooms: { title: 'חדרים ויעדים', desc: 'ניהול יעדים ומיקומם' },
      routes: { title: 'נקודות מסלול', desc: 'ניהול צמתי ניווט וחיבורים' },
      locationCodes: { title: 'קודי מיקום', desc: 'נקודות התחלה של ברקוד/QR' },
      analysis: { title: 'ניתוח סמנטי', desc: 'הרצה וסקירה של ניתוח המפה' },
      cleanup: { title: 'ניקוי נתוני ניווט', desc: 'הסרת נתונים שנוצרו או איפוס ניווט' },
    },
  },
};

export default dashboardUi;
